image: milanpopovic/pylinter:2.7.13



stages:
  - test
  - build
  - run


Linter:
  stage: test
  script: pylint --disable=invalid-name,E0401 --output-format=parseable *.py

Octoprint Install:
  stage: build
  image: octoprint/octoprint:1.3.10rc2
  script: source /opt/octoprint/venv/bin/activate && python setup.py install

Octoprint install and test:
  stage: run
  image: milanpopovic/octoprint:1.3.10rc2
  before_script:
    - touch /dev/i2c-1
  script: bash octoprint_LCD1602/tests/running_test.sh